export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const FETCH_ARTIST = 'FETCH_ARTIST'
export const CURRENT_ARTIST = "CURRENT_ARTIST";
export const CURRENT_IMAGE = 'CURRENT_IMAGE'
export const SET_CURRENT_ARTIST = 'SET_CURRENT_ARTIST'
export const RESET_TRACKS = "RESET_TRACKS"
export const RESET_STATE = 'RESET_STATE'